### ISSUE TITLE
Dataowner conversation language and format

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#155]
- Format the conversation more properly, currently it's not very readable as well fields are embedded within the text.
- The conversation should be in the same language as the previous conversation.

**Comment by ErezSha** [comment]
@asaf same language as earlier conversation needs another llm call.
Are you okay with that?

**Comment by ErezSha** [comment]
@asaf I made changes to the format. Hope it's better.

**Comment by asaf** [comment]
@ErezSha I guess another call is too much for this atm, i'll try the formatted changes.
