### ISSUE TITLE
All DB tables must have org_id key

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#20]
Important when using DBs such as Azure CosmosDB where _org_id is the distribution key required for table colocation.

- [x] Add _org_id_ column
- [ ] For security reasons, add to all relevant APIs (probably mostly facades) _org_id_ where condition

**Comment by ErezSha** [comment]
Some [context for distribution key](https://learn.microsoft.com/en-us/training/modules/design-multi-tenant-saas-apps-with-azure-cosmos-db-for-postgresql/4-distribute-tables-with-minimal-app-disruption):
Composite foreign key
```
class Book(Base):
    __tablename__ = 'books'
    title = Column(String(20), primary_key=True)
    author_firstName = Column(String(20))
    author_lastName = Column(String(20))
    __table_args__ = (ForeignKeyConstraint([author_firstName, author_lastName], [Author.firstName, Author.lastName]),{})
```

composite primary key
```
class Book(Base):
    __tablename__ = 'books'
    title = Column(String(20), primary_key=True)
    author_firstName = Column(String(20), primary_key=True)
```

creating distributed tables
```
SELECT create_distributed_table('org', 'id');  //create_distributed_table_concurrently()
SELECT create_distributed_table('request', 'org_id', colocate_with => 'org');
SELECT create_distributed_table('message', 'org_id', colocate_with => 'org');
```

**Comment by ErezSha** [comment]
@asaf This is currently an issue, because `org_id` is nullable on both `request` and `message` tables.
Primary key can't be nullable.
We'll have to decide what we want to do about the "global" org before we can commit anything for this issue.

**Comment by asaf** [comment]
@ErezSha what's left here? agreed not to allow null org_id as `global` is going to be a tenant,
Please make sure all `org_id` fields are not nullable and resolve the ticket.
