### ISSUE TITLE
Secure endpoints

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#53]
- Secure endpoints using scopes while standardizing granularity.

#### Scope Required: `update:workspaces`
Note: Not sure about this as any authenticated user can create a workspace.

#### Scope Required: `read:conversations`
Note: admin can read any, non admin - need to add a criteria where `current_user eq assignee`

#### Scope Required: `read:conversations`
Note: same as list

#### Scope Required: `update:conversations`
Note: admin can cancel any, otherwise `current_user eq assignee`

#### Scope Required: `read:secrets`

**Comment by asaf** [comment]
@ErezSha anything left about this ticket?

**Comment by ErezSha** [comment]
@asaf What do you want for authz? scopes?

**Comment by asaf** [comment]
This is far away from being completed, we need minimal security facilities.

**Comment by asaf** [comment]
@ErezSha please implement, per your preference - come up with any solution (inline checking, decorators, fastapi dependencies, etc.

Please note that few of the endpoints requires a bit more work than just checking the scope as it depends if the user is an admin or not.


I suggest to come up with some method such 'is_admin' which we can for now resolve by the creator of the workspace and later on provide a more robust implementation based on user roles/scopes/etc.

**Comment by ErezSha** [comment]
Reminder:
Auth0 is a bit weird with scopes, because scopes is per audience, so we'll probably have to create a different audience per workspace.

**Comment by asaf** [comment]
Can't we create a single API for the bot?

Then the access granting should be on the org level, e.g a user in org
"acme" should have read: workspaces.

Granting on the user level does not make any sense.

**Comment by ErezSha** [comment]
From what I understand, in Auth0, scopes are on the api level, not org level.

**Comment by asaf** [comment]
Not the definition of the scopes, the relationship to the users
