### ISSUE TITLE
Using workspace id as table names is error prone

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#54]
```
sqlite3.OperationalError: unrecognized token: "2h0iSH01EV_data"
```

**Comment by ErezSha** [comment]
@asaf This is probably an issue only on sqlite.
You can just change the store's name to `data_{id}` instead of `{id}_data`

**Comment by asaf** [comment]
This is starting to be a more general problem, multiple services requires some more restrictive names (currently facing an issue with custom certificate for domains that must be only lowercase letters.

we can keep trying to "tweak" the workspace_id into a key that services accepts or come up with another value that fits the all (if possible at all)

**Comment by asaf** [comment]
The other alternative is to have another ID that the user should provide that is only _letters and digits_ and we agreed that it's annoying to ask the user for a unique id. for now we go with translating the id to the service.

**Comment by asaf** [comment]
Re-opening as we introduced an alpha-numeric field on the workspace level which can be used in services now.
