### ISSUE TITLE
Cancel a conversation 

### ISSUE THREAD

**Issue by asaf** [crossid/accessbot#80]
**Is your feature request related to a problem?
The bot may start irrelevant / inappropriate threads, which may need to be cancelled immediately.

**Describe the solution you'd like**
A new endpoint to cancel a conversation, if a conversation is chained to another than the second conversation should be cancelled as well.

**Comment by ErezSha** [comment]
I put the api endpoint at `post /{id}/.cancel` to leave `delete /{id}` for archiving

**Comment by asaf** [comment]
@ErezSha I think you forgot to create a branch/PR

**Comment by asaf** [comment]
> I put the api endpoint at `patch /{id}/.cancel` to leave `delete /{id}` for archiving

Why patch and not post? usually actions are POST.
